bids_root: F:/BIDS_TUSZ
data_size: 0.01
dataset: BIDS_TUSZ
debug: true
epoch_duration: 8
epoch_ratios:
  bckg: 1
  interictal: 2
  sz: 2
generate_timescoring_plots: true
inference: false
load_model: true
load_preprocessed_data: true
max_workers: 4
mne_preload: false
mne_verbose: false
model_dir: ./models
model_name: fft_de
model_type: detach_rocket
num_kernels: 10000
num_models: 10
preprocessed_dir: ./preprocessed
result_dir: ./results
sample_rate: 128
sample_seed: 42
save_model: true
save_preprocessed_data: true
seizure_event_type:
- sz
split_ratio: 0.8
split_seed: 42
threshold: 0.5
timestamp: 0802_024621
